version: 2
services:
  app:
    image: api-test-natahouse-production
    environment:
      NODE_ENV: production
      PORT: 80
      LOGGER_LEVEL: info
      mongoDB: mongodb+srv://useraccess:4UGcUNVI1oNUglSB@cluster0-i1knx.mongodb.net/natahouse?retryWrites=true&w=majority
      secret: 1THOb69WGiK8SnNg2niM5pw4CWjf7kRE
      swapiBaseURL: https://swapi.co/api/
    ports:
      - 8001:80/tcp
  app-dev:
    image: api-test-natahouse-development
    environment: 
      NODE_ENV: development
      PORT: 80
      LOGGER_LEVEL: debug
      mongoDB: mongodb+srv://useraccess:4UGcUNVI1oNUglSB@cluster0-i1knx.mongodb.net/natahouse?retryWrites=true&w=majority
      secret: AGmFyMMlRzPwE3r6XmLSJmyOf2t1IZh6
      swapiBaseURL: https://swapi.co/api/
    ports:
      - 3001:80/tcp
